# query_class_analysis.py
# ========================
# This script reads the already-computed outputs from part5.py and does
# a deeper class-level breakdown of the results. We need this for the report
# because the professor's schematic says: "for which CLASS did this happen."
#
# We classify queries by two different axes:
#   1) Query Length  : short (<=5 words), medium (6-10 words), long (>=11 words)
#   2) Qrel Density  : sparse (1-3 relevant docs), medium (4-9), dense (>=10)
#
# We also find universal failures (queries where every single method scores AP=0)
# and do a breakdown of PRF-vs-BM25 and LSA-vs-BM25 to explain marginal gaps.
#
# Inputs (all from output/ folder, generated by part5.py):
#   output/part5_full_per_query_ap.json   <- full per-query AP for all systems
#   output/part5_failure_analysis.json    <- existing failure data
#   cranfield/cran_queries.json           <- raw query text
#   cranfield/cran_qrels.json             <- relevance data for density
#
# Outputs saved to output/:
#   part5_query_length_class_analysis.json
#   part5_query_density_class_analysis.json
#   part5_length_class_chart.png
#   part5_density_class_chart.png
#   part5_universal_failures.json
#   part5_prf_vs_bm25_breakdown.json
#   part5_lsa_vs_bm25_breakdown.json
#   part5_failure_boundary_conditions.json

import json
import os
import math
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Path configuration - same as part5.py
DATASET_PATH = 'cranfield/'
OUT_DIR = 'output/'


# ===========================================================================
# HELPER: Load JSON file
# ===========================================================================

def load_json_file(path):
    """
    This function loads a JSON file and returns the data.
    Let us keep this simple and explicit.
    """
    f = open(path, 'r')
    data = json.load(f)
    f.close()
    return data


# ===========================================================================
# HELPER: Save JSON file
# ===========================================================================

def save_json_file(data, path):
    """
    This function saves the given data as a JSON file at the given path.
    We use indent=4 so it is easy to read later.
    """
    f = open(path, 'w')
    json.dump(data, f, indent=4)
    f.close()
    print("  Saved:", path)


# ===========================================================================
# STEP 1: Determine query length group for each query
# ===========================================================================

def get_query_length_groups(all_queries_list):
    """
    This function assigns each query to a length group based on word count.
    We count the raw word count (splitting on spaces) of the query text.

    Groups:
      short  : <= 5 words
      medium : 6 to 10 words
      long   : >= 11 words

    Returns a dictionary: {query_id -> {"length_words": N, "length_group": "..."}}
    """
    length_info = {}

    for i in range(len(all_queries_list)):
        q_entry = all_queries_list[i]
        q_id = int(q_entry["query number"])
        q_text = q_entry["query"]

        # Count words by splitting on whitespace
        words = q_text.strip().split()
        num_words = len(words)

        # Now deciding the group
        if num_words <= 5:
            group_name = "short"
        elif num_words <= 10:
            group_name = "medium"
        else:
            group_name = "long"

        length_info[q_id] = {
            "length_words": num_words,
            "length_group": group_name,
            "query_text": q_text
        }

    return length_info


# ===========================================================================
# STEP 2: Determine qrel density group for each query
# ===========================================================================

def get_qrel_density_groups(all_qrels_list):
    """
    This function counts how many relevant documents each query has in qrels.
    A document is relevant if its position is 1, 2, 3, or 4.

    Groups:
      sparse : 1 to 3 relevant documents
      medium : 4 to 9 relevant documents
      dense  : >= 10 relevant documents

    Returns a dictionary: {query_id -> {"relevant_count": N, "density_group": "..."}}
    """
    # First we count how many relevant docs each query has
    relevant_count_per_query = {}

    for i in range(len(all_qrels_list)):
        entry = all_qrels_list[i]
        q_id = int(entry["query_num"])
        pos = entry["position"]

        # Only count if position indicates relevance
        if pos == 1 or pos == 2 or pos == 3 or pos == 4:
            if q_id not in relevant_count_per_query:
                relevant_count_per_query[q_id] = 0
            relevant_count_per_query[q_id] = relevant_count_per_query[q_id] + 1

    # Now assign density group based on count
    density_info = {}

    for q_id in relevant_count_per_query:
        count = relevant_count_per_query[q_id]

        if count <= 3:
            group_name = "sparse"
        elif count <= 9:
            group_name = "medium"
        else:
            group_name = "dense"

        density_info[q_id] = {
            "relevant_count": count,
            "density_group": group_name
        }

    return density_info


# ===========================================================================
# STEP 3: Compute per-class average AP for each system
# ===========================================================================

def compute_class_ap(per_query_ap_data, query_ids_list, class_info_dict, class_key):
    """
    This function computes the average AP for each system broken down by class.
    For example, class_key = "length_group" gives us AP per (system, short/medium/long) pair.

    Parameters:
      per_query_ap_data : dict with "query_ids" list and system_name -> [ap values]
      query_ids_list    : ordered list of query IDs matching the AP lists
      class_info_dict   : {query_id -> {class_key: "short"/"medium"/etc, ...}}
      class_key         : the key to use for grouping ("length_group" or "density_group")

    Returns: {system_name -> {class_value -> {"count": N, "mean_ap": V}}}
    """
    # First let us find all the unique class values
    all_class_values = []
    for q_id in class_info_dict:
        class_val = class_info_dict[q_id][class_key]
        if class_val not in all_class_values:
            all_class_values.append(class_val)

    # Get the list of system names from the data
    system_names = []
    for key in per_query_ap_data.keys():
        if key != "query_ids":
            system_names.append(key)

    # For each system, for each class value, accumulate AP values
    result = {}

    for sys_idx in range(len(system_names)):
        sys_name = system_names[sys_idx]
        ap_list = per_query_ap_data[sys_name]

        # Initialize storage for each class
        class_ap_sums = {}
        class_counts = {}
        for cv in all_class_values:
            class_ap_sums[cv] = 0.0
            class_counts[cv] = 0

        # Go through all queries and accumulate
        for q_idx in range(len(query_ids_list)):
            q_id = query_ids_list[q_idx]
            ap_val = ap_list[q_idx]

            # Check if this query has class info
            if q_id in class_info_dict:
                class_val = class_info_dict[q_id][class_key]
                class_ap_sums[class_val] = class_ap_sums[class_val] + ap_val
                class_counts[class_val] = class_counts[class_val] + 1

        # Compute the mean AP for each class
        sys_result = {}
        for cv in all_class_values:
            if class_counts[cv] > 0:
                mean_ap = class_ap_sums[cv] / float(class_counts[cv])
            else:
                mean_ap = 0.0
            sys_result[cv] = {
                "count": class_counts[cv],
                "mean_ap": round(mean_ap, 4)
            }

        result[sys_name] = sys_result

    return result


# ===========================================================================
# STEP 4: Also add baseline (VSM) to the class analysis
# ===========================================================================

def add_baseline_to_class_ap(class_ap_result, per_query_ap_data, query_ids_list, class_info_dict, class_key):
    """
    The per_query_ap_data has VSM (Baseline) as a key too.
    This function adds it to the class analysis result dict.
    We handle it separately because the structure may differ.
    """
    # Check if baseline is in the data
    baseline_key = "VSM (Baseline)"
    if baseline_key not in per_query_ap_data:
        print("  Warning: VSM (Baseline) not found in per_query_ap_data")
        return class_ap_result

    # We will call compute_class_ap on just the baseline data
    # But since compute_class_ap iterates all non-query_ids keys, it will include it
    # So basically we just need to make sure it was included. Let's check.
    if baseline_key in class_ap_result:
        print("  Baseline already included in result.")
    else:
        print("  Note: VSM (Baseline) was not in class result, it may already be included.")

    return class_ap_result


# ===========================================================================
# STEP 5: Plot class analysis bar charts
# ===========================================================================

def plot_class_bar_chart(class_ap_result, class_order, chart_title, x_label, out_path):
    """
    This function creates a grouped bar chart showing mean AP@10 for each
    system broken down by class group.

    class_ap_result : result from compute_class_ap
    class_order     : ordered list of class values to show on x-axis
    chart_title     : title for the plot
    x_label         : label for x axis
    out_path        : where to save the image
    """
    # Get system names from result
    system_names = list(class_ap_result.keys())
    num_systems = len(system_names)
    num_classes = len(class_order)

    # We will place bars side by side for each class group
    bar_width = 0.8 / float(num_systems)

    fig, ax = plt.subplots(figsize=(12, 6))

    # x positions for the groups
    x_positions = []
    for i in range(num_classes):
        x_positions.append(float(i))

    # Drawing bars for each system
    for sys_idx in range(num_systems):
        sys_name = system_names[sys_idx]
        sys_data = class_ap_result[sys_name]

        # Collecting mean AP values in the correct class order
        map_values = []
        for cv in class_order:
            if cv in sys_data:
                map_values.append(sys_data[cv]["mean_ap"])
            else:
                map_values.append(0.0)

        # Calculate bar positions
        bar_positions = []
        for i in range(len(x_positions)):
            offset = (sys_idx - num_systems / 2.0 + 0.5) * bar_width
            bar_positions.append(x_positions[i] + offset)

        ax.bar(bar_positions, map_values, bar_width, label=sys_name)

    ax.set_xticks(x_positions)
    ax.set_xticklabels(class_order)
    ax.set_xlabel(x_label)
    ax.set_ylabel("Mean AP@10")
    ax.set_title(chart_title)
    ax.legend(loc='upper right', fontsize=7)
    ax.grid(axis='y', alpha=0.4)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()
    print("  Saved chart:", out_path)


# ===========================================================================
# STEP 6: Find universal failures
# ===========================================================================

def find_universal_failures(per_query_ap_data, query_ids_list, length_info, density_info, all_queries_list):
    """
    This function finds queries where EVERY system (including baseline) scores AP@10 = 0.
    These are the hardest queries - nothing works on them.
    We also record query text, length, and density info to help explain why.
    """
    # Get all system names including baseline
    system_names = []
    for key in per_query_ap_data.keys():
        if key != "query_ids":
            system_names.append(key)

    # Build a quick lookup: query_id -> raw text
    raw_text_dict = {}
    for q_entry in all_queries_list:
        raw_text_dict[int(q_entry["query number"])] = q_entry["query"]

    universal_failures = []

    for q_idx in range(len(query_ids_list)):
        q_id = query_ids_list[q_idx]

        # Check if ALL systems score 0 for this query
        all_zero = True
        for sys_idx in range(len(system_names)):
            sys_name = system_names[sys_idx]
            ap_val = per_query_ap_data[sys_name][q_idx]
            if ap_val > 0.001:
                all_zero = False
                break

        if all_zero == True:
            # This query is a universal failure
            entry = {
                "query_id": q_id,
                "query_text": raw_text_dict.get(q_id, "N/A")
            }

            # Adding length info if available
            if q_id in length_info:
                entry["length_words"] = length_info[q_id]["length_words"]
                entry["length_group"] = length_info[q_id]["length_group"]
            else:
                entry["length_words"] = -1
                entry["length_group"] = "unknown"

            # Adding density info if available
            if q_id in density_info:
                entry["relevant_count"] = density_info[q_id]["relevant_count"]
                entry["density_group"] = density_info[q_id]["density_group"]
            else:
                entry["relevant_count"] = 0
                entry["density_group"] = "no_qrels"

            universal_failures.append(entry)

    return universal_failures


# ===========================================================================
# STEP 7: Marginal gap breakdown (PRF vs BM25 and LSA vs BM25)
# ===========================================================================

def compute_marginal_gap_breakdown(per_query_ap_data, query_ids_list,
                                   length_info, density_info,
                                   system_a_name, system_b_name):
    """
    For two systems A and B that have a marginal MAP difference, this function
    breaks down on which types of queries A beats B and vice versa.
    This helps explain mechanistically WHY one system marginally beats the other.

    Returns a dict with breakdown by length group and density group.
    """
    # Check that both systems are in the data
    if system_a_name not in per_query_ap_data:
        print("  Warning:", system_a_name, "not in per_query_ap_data")
        return {}
    if system_b_name not in per_query_ap_data:
        print("  Warning:", system_b_name, "not in per_query_ap_data")
        return {}

    ap_a = per_query_ap_data[system_a_name]
    ap_b = per_query_ap_data[system_b_name]

    # For each length group and density group, count A wins, B wins, ties
    length_groups = ["short", "medium", "long"]
    density_groups = ["sparse", "medium", "dense"]

    # Initialize counters for length breakdown
    length_breakdown = {}
    for lg in length_groups:
        length_breakdown[lg] = {"a_wins": 0, "b_wins": 0, "ties": 0, "count": 0}

    # Initialize counters for density breakdown
    density_breakdown = {}
    for dg in density_groups:
        density_breakdown[dg] = {"a_wins": 0, "b_wins": 0, "ties": 0, "count": 0}

    # Iterate through all queries
    for q_idx in range(len(query_ids_list)):
        q_id = query_ids_list[q_idx]
        ap_val_a = ap_a[q_idx]
        ap_val_b = ap_b[q_idx]

        # Determine who wins this query
        if ap_val_a > ap_val_b + 0.001:
            winner = "a"
        elif ap_val_b > ap_val_a + 0.001:
            winner = "b"
        else:
            winner = "tie"

        # Update length breakdown
        if q_id in length_info:
            lg = length_info[q_id]["length_group"]
            if lg in length_breakdown:
                length_breakdown[lg]["count"] = length_breakdown[lg]["count"] + 1
                if winner == "a":
                    length_breakdown[lg]["a_wins"] = length_breakdown[lg]["a_wins"] + 1
                elif winner == "b":
                    length_breakdown[lg]["b_wins"] = length_breakdown[lg]["b_wins"] + 1
                else:
                    length_breakdown[lg]["ties"] = length_breakdown[lg]["ties"] + 1

        # Update density breakdown
        if q_id in density_info:
            dg = density_info[q_id]["density_group"]
            if dg in density_breakdown:
                density_breakdown[dg]["count"] = density_breakdown[dg]["count"] + 1
                if winner == "a":
                    density_breakdown[dg]["a_wins"] = density_breakdown[dg]["a_wins"] + 1
                elif winner == "b":
                    density_breakdown[dg]["b_wins"] = density_breakdown[dg]["b_wins"] + 1
                else:
                    density_breakdown[dg]["ties"] = density_breakdown[dg]["ties"] + 1

    # Also compute win percentages for easy reading
    for lg in length_breakdown:
        total = length_breakdown[lg]["count"]
        if total > 0:
            a_pct = round(100.0 * length_breakdown[lg]["a_wins"] / float(total), 1)
            b_pct = round(100.0 * length_breakdown[lg]["b_wins"] / float(total), 1)
            length_breakdown[lg]["a_win_pct"] = a_pct
            length_breakdown[lg]["b_win_pct"] = b_pct
        else:
            length_breakdown[lg]["a_win_pct"] = 0.0
            length_breakdown[lg]["b_win_pct"] = 0.0

    for dg in density_breakdown:
        total = density_breakdown[dg]["count"]
        if total > 0:
            a_pct = round(100.0 * density_breakdown[dg]["a_wins"] / float(total), 1)
            b_pct = round(100.0 * density_breakdown[dg]["b_wins"] / float(total), 1)
            density_breakdown[dg]["a_win_pct"] = a_pct
            density_breakdown[dg]["b_win_pct"] = b_pct
        else:
            density_breakdown[dg]["a_win_pct"] = 0.0
            density_breakdown[dg]["b_win_pct"] = 0.0

    result = {
        "system_a": system_a_name,
        "system_b": system_b_name,
        "by_query_length": length_breakdown,
        "by_qrel_density": density_breakdown
    }

    return result


# ===========================================================================
# STEP 8: Enrich failure analysis with class information
# ===========================================================================

def enrich_failure_analysis(failure_report, length_info, density_info):
    """
    This function takes the existing failure analysis from part5.py and
    adds length_group and density_group info to each failure entry.
    This tells us under what boundary conditions each method fails.
    """
    enriched = {}

    system_names = list(failure_report.keys())

    for sys_idx in range(len(system_names)):
        sys_name = system_names[sys_idx]
        sys_data = failure_report[sys_name]

        new_failures_list = sys_data["new_failures"]

        # Count failures by length group
        length_fail_counts = {"short": 0, "medium": 0, "long": 0}
        density_fail_counts = {"sparse": 0, "medium": 0, "dense": 0}

        enriched_new_failures = []
        for fail_idx in range(len(new_failures_list)):
            fail_entry = new_failures_list[fail_idx]
            q_id = fail_entry["query_id"]

            enriched_entry = {}
            for k in fail_entry:
                enriched_entry[k] = fail_entry[k]

            # Adding length info
            if q_id in length_info:
                enriched_entry["length_group"] = length_info[q_id]["length_group"]
                enriched_entry["length_words"] = length_info[q_id]["length_words"]
                lg = length_info[q_id]["length_group"]
                if lg in length_fail_counts:
                    length_fail_counts[lg] = length_fail_counts[lg] + 1
            else:
                enriched_entry["length_group"] = "unknown"
                enriched_entry["length_words"] = -1

            # Adding density info
            if q_id in density_info:
                enriched_entry["density_group"] = density_info[q_id]["density_group"]
                enriched_entry["relevant_count"] = density_info[q_id]["relevant_count"]
                dg = density_info[q_id]["density_group"]
                if dg in density_fail_counts:
                    density_fail_counts[dg] = density_fail_counts[dg] + 1
            else:
                enriched_entry["density_group"] = "unknown"
                enriched_entry["relevant_count"] = -1

            enriched_new_failures.append(enriched_entry)

        enriched[sys_name] = {
            "new_failures_count": sys_data["new_failures_count"],
            "fixed_failures_count": sys_data["fixed_failures_count"],
            "failures_by_length_group": length_fail_counts,
            "failures_by_density_group": density_fail_counts,
            "new_failures": enriched_new_failures,
            "fixed_failures": sys_data["fixed_failures"]
        }

    return enriched


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    print("=" * 60)
    print("Query Class Analysis Script")
    print("=" * 60)

    # Check that the required output folder exists
    if not os.path.exists(OUT_DIR):
        os.makedirs(OUT_DIR)

    # ── Load all required input data ─────────────────────────────────────────
    print("\n[1/7] Loading input data...")

    # We need to check if the full per-query AP file exists
    full_pq_ap_path = OUT_DIR + "part5_full_per_query_ap.json"
    if not os.path.exists(full_pq_ap_path):
        print("  ERROR: File not found:", full_pq_ap_path)
        print("  Please run part5.py first to generate this file.")
        return

    per_query_ap_data = load_json_file(full_pq_ap_path)
    query_ids_list = per_query_ap_data["query_ids"]
    print("  Loaded per-query AP for", len(query_ids_list), "queries")
    print("  Systems found:", [k for k in per_query_ap_data.keys() if k != "query_ids"])

    # Load raw cranfield queries
    all_queries = load_json_file(DATASET_PATH + "cran_queries.json")
    print("  Loaded", len(all_queries), "raw queries")

    # Load qrels
    all_qrels = load_json_file(DATASET_PATH + "cran_qrels.json")
    print("  Loaded", len(all_qrels), "qrel entries")

    # Load existing failure analysis
    failure_report = load_json_file(OUT_DIR + "part5_failure_analysis.json")
    print("  Loaded existing failure analysis")

    # ── Step 1: Compute query length groups ──────────────────────────────────
    print("\n[2/7] Computing query length groups...")
    length_info = get_query_length_groups(all_queries)

    # Counting how many queries are in each group
    short_count = 0
    medium_count = 0
    long_count = 0
    for q_id in length_info:
        grp = length_info[q_id]["length_group"]
        if grp == "short":
            short_count = short_count + 1
        elif grp == "medium":
            medium_count = medium_count + 1
        else:
            long_count = long_count + 1

    print("  Short queries (<=5 words):", short_count)
    print("  Medium queries (6-10 words):", medium_count)
    print("  Long queries (>=11 words):", long_count)

    # ── Step 2: Compute qrel density groups ──────────────────────────────────
    print("\n[3/7] Computing qrel density groups...")
    density_info = get_qrel_density_groups(all_qrels)

    # Counting how many queries are in each density group
    sparse_count = 0
    medium_den_count = 0
    dense_count = 0
    no_qrel_count = 0
    for q_id in query_ids_list:
        if q_id in density_info:
            dg = density_info[q_id]["density_group"]
            if dg == "sparse":
                sparse_count = sparse_count + 1
            elif dg == "medium":
                medium_den_count = medium_den_count + 1
            else:
                dense_count = dense_count + 1
        else:
            no_qrel_count = no_qrel_count + 1

    print("  Sparse (1-3 relevant docs):", sparse_count)
    print("  Medium (4-9 relevant docs):", medium_den_count)
    print("  Dense (>=10 relevant docs):", dense_count)
    print("  No qrel entry:", no_qrel_count)

    # ── Step 3: Compute per-class AP analysis ─────────────────────────────────
    print("\n[4/7] Computing per-class AP analysis...")

    # Length class analysis
    print("  Computing length-class AP breakdown...")
    length_class_ap = compute_class_ap(
        per_query_ap_data, query_ids_list, length_info, "length_group"
    )

    # Density class analysis
    print("  Computing density-class AP breakdown...")
    density_class_ap = compute_class_ap(
        per_query_ap_data, query_ids_list, density_info, "density_group"
    )

    # Printing a quick summary so we can verify it looks right
    print("\n  --- Length Class Analysis (MAP@10 by query length) ---")
    sys_names_for_print = list(length_class_ap.keys())
    print("  {:25s} {:>10s} {:>10s} {:>10s}".format("System", "Short", "Medium", "Long"))
    for s in sys_names_for_print:
        sh = length_class_ap[s].get("short", {}).get("mean_ap", 0.0)
        me = length_class_ap[s].get("medium", {}).get("mean_ap", 0.0)
        lo = length_class_ap[s].get("long", {}).get("mean_ap", 0.0)
        print("  {:25s} {:>10.4f} {:>10.4f} {:>10.4f}".format(s[:25], sh, me, lo))

    print("\n  --- Density Class Analysis (MAP@10 by qrel density) ---")
    print("  {:25s} {:>10s} {:>10s} {:>10s}".format("System", "Sparse", "Medium", "Dense"))
    for s in sys_names_for_print:
        sp = density_class_ap[s].get("sparse", {}).get("mean_ap", 0.0)
        me = density_class_ap[s].get("medium", {}).get("mean_ap", 0.0)
        de = density_class_ap[s].get("dense", {}).get("mean_ap", 0.0)
        print("  {:25s} {:>10.4f} {:>10.4f} {:>10.4f}".format(s[:25], sp, me, de))

    # ── Step 4: Plot class bar charts ─────────────────────────────────────────
    print("\n[5/7] Generating class analysis charts...")

    plot_class_bar_chart(
        length_class_ap,
        class_order=["short", "medium", "long"],
        chart_title="Mean AP@10 by Query Length Group — All Systems",
        x_label="Query Length Group",
        out_path=OUT_DIR + "part5_length_class_chart.png"
    )

    plot_class_bar_chart(
        density_class_ap,
        class_order=["sparse", "medium", "dense"],
        chart_title="Mean AP@10 by Qrel Density Group — All Systems",
        x_label="Qrel Density Group (Number of Relevant Documents)",
        out_path=OUT_DIR + "part5_density_class_chart.png"
    )

    # ── Step 5: Universal failures ───────────────────────────────────────────
    print("\n[5b/7] Finding universal failures (AP=0 for all systems)...")
    universal_failures = find_universal_failures(
        per_query_ap_data, query_ids_list, length_info, density_info, all_queries
    )
    print("  Found", len(universal_failures), "queries where ALL systems score AP@10 = 0")
    for uf in universal_failures:
        print("    Query", uf["query_id"], "(" + uf["length_group"] + ",",
              uf.get("density_group", "?") + "):", uf["query_text"][:70])

    # ── Step 6: Marginal gap breakdowns ──────────────────────────────────────
    print("\n[6/7] Computing marginal gap breakdowns...")

    # BM25+PRF vs BM25 (0.83% MAP gap from our results)
    prf_vs_bm25 = compute_marginal_gap_breakdown(
        per_query_ap_data, query_ids_list,
        length_info, density_info,
        "BM25 + PRF", "BM25"
    )
    print("  PRF vs BM25 breakdown computed.")
    print("  By length:")
    for lg in prf_vs_bm25["by_query_length"]:
        entry = prf_vs_bm25["by_query_length"][lg]
        print("    " + lg + ": PRF wins", entry["a_wins"], "(" + str(entry["a_win_pct"]) + "%)",
              "BM25 wins", entry["b_wins"], "(" + str(entry["b_win_pct"]) + "%)")
    print("  By density:")
    for dg in prf_vs_bm25["by_qrel_density"]:
        entry = prf_vs_bm25["by_qrel_density"][dg]
        print("    " + dg + ": PRF wins", entry["a_wins"], "(" + str(entry["a_win_pct"]) + "%)",
              "BM25 wins", entry["b_wins"], "(" + str(entry["b_win_pct"]) + "%)")

    # BM25 vs LSA (0.71% MAP gap)
    bm25_vs_lsa = compute_marginal_gap_breakdown(
        per_query_ap_data, query_ids_list,
        length_info, density_info,
        "BM25", "LSA (k=200, CV)"
    )
    print("\n  BM25 vs LSA breakdown computed.")
    print("  By length:")
    for lg in bm25_vs_lsa["by_query_length"]:
        entry = bm25_vs_lsa["by_query_length"][lg]
        print("    " + lg + ": BM25 wins", entry["a_wins"], "(" + str(entry["a_win_pct"]) + "%)",
              "LSA wins", entry["b_wins"], "(" + str(entry["b_win_pct"]) + "%)")

    # ── Step 7: Enrich failure analysis ──────────────────────────────────────
    print("\n[7/7] Enriching failure analysis with boundary conditions...")
    enriched_failures = enrich_failure_analysis(failure_report, length_info, density_info)

    print("  Boundary condition summary:")
    for sys_name in enriched_failures:
        fr = enriched_failures[sys_name]
        if fr["new_failures_count"] > 0:
            print("  " + sys_name + " new failures by length:", fr["failures_by_length_group"])
            print("  " + sys_name + " new failures by density:", fr["failures_by_density_group"])

    # ── Save all outputs ──────────────────────────────────────────────────────
    print("\n[Saving] Writing all outputs to disk...")

    save_json_file(length_class_ap, OUT_DIR + "part5_query_length_class_analysis.json")
    save_json_file(density_class_ap, OUT_DIR + "part5_query_density_class_analysis.json")
    save_json_file(universal_failures, OUT_DIR + "part5_universal_failures.json")
    save_json_file(prf_vs_bm25, OUT_DIR + "part5_prf_vs_bm25_breakdown.json")
    save_json_file(bm25_vs_lsa, OUT_DIR + "part5_lsa_vs_bm25_breakdown.json")
    save_json_file(enriched_failures, OUT_DIR + "part5_failure_boundary_conditions.json")

    # Also save length and density info for reference
    save_json_file(length_info, OUT_DIR + "part5_query_length_info.json")
    save_json_file(density_info, OUT_DIR + "part5_query_density_info.json")

    print("\n" + "=" * 60)
    print("DONE. All analysis saved to output/")
    print("=" * 60)


if __name__ == '__main__':
    main()
